[package]
name = "db_model"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
diesel = { version = "2.2.0", features = ["mysql", "chrono", "mysql_backend", "time"] }
dotenvy = "0.15"
snowflake = "1.3.0"
time = "0.3.44"
uuid = { version = "1.19.0", features = ["v8", "v4"] }

